### PR TITLE
Modernize the recipe

### PR DESCRIPTION
**Pull request by jakirkham**
This modernizes the recipe in a number of ways.
- Tries to match the [example `meta.yaml`](https://github.com/conda-forge/staged-recipes/blob/4f038b4664262faefafd98df59c279e8556a40eb/recipes/example/meta.yaml).
- Uses [pypi.io](https://pypi.io) for downloads.
- Switches to using the `sha256` checksum from [pypi.io](https://pypi.io).
- Includes the license file in the package.
- Adds in some optional metadata.
- Uses the `toolchain`.
- Re-rendered with `conda-smithy` version `1.3.0`.

### CODE REVIEW

**Comment by jakirkham** [comment]
Needs a re-rendering too.

**Comment by jakirkham** [comment]
Please let me know if you have any thoughts on this, @luispedro. Particularly on the optional metadata. Maybe you have ideas of better information to add there.

**Comment by luispedro** [comment]
This looks good. I normally use the more informative read the docs link as Homepage : http://mahotas.readthedocs.io/ but the provided links works too.

**Comment by jakirkham** [comment]
Ok, was thinking about that. Will update.

**Pull request merged**
